import argparse
import logging
import sys

from .analysis import run_analysis, cluster_pathways
from .visualize import run_visualization

def setup_logging():
    logging.basicConfig(
        level=logging.INFO,
        format='%(asctime)s - %(name)s - %(levelname)s - %(message)s',
        stream=sys.stdout
    )

def main():
    setup_logging()
    parser = argparse.ArgumentParser(description="Gephyra: A network-graph and Fréchet clustering framework for water network detection.")
    subparsers = parser.add_subparsers(dest="command", help="Sub-commands")
    subparsers.required = True

    # --- Calculate Subcommand ---
    calc_parser = subparsers.add_parser("calculate", help="Analyze trajectory to find water networks.")
    calc_parser.add_argument("--topo", required=True, help="Topology file (e.g., .pdb, .tpr).")
    calc_parser.add_argument("--traj", required=False, help="Trajectory file (e.g., .xtc, .dcd). If not provided, evaluates only topology.")
    calc_parser.add_argument("--root", required=True, help="MDAnalysis selection string for the root atoms (e.g., 'resname LIG').")
    calc_parser.add_argument("--water", default="resname SOL or resname WAT or resname HOH", help="MDAnalysis selection string for water.")
    calc_parser.add_argument("--stride", type=int, default=1, help="Frame stride for trajectory processing.")
    calc_parser.add_argument("--max_depth", type=int, default=10, help="Maximum number of consecutive waters in a path.")
    calc_parser.add_argument("--min_depth", type=int, default=1, help="Minimum number of consecutive waters in a path to save in results.")
    calc_parser.add_argument("--cooperativity", type=float, default=0.92, help="Depth-dependent cooperativity factor for hydrogen bonds.")
    calc_parser.add_argument("--coarse_cutoff", type=float, default=4.5, help="Coarse distance cutoff (Angstroms) for initial graph building.")
    calc_parser.add_argument("--output", default="results.jsonl", help="Output JSON Lines file for storing the raw network data.")
    calc_parser.add_argument("--csv", default=None, help="Optional output CSV file for storing human-readable summary data.")

    # --cluster / --cluster_threshold are kept for backward compatibility but are deprecated in favour of the dedicated 'cluster' sub-command below.
    # Their defaults are kept identical to the 'cluster' sub-command so that the two routes give the same result.
    calc_parser.add_argument("--cluster", action="store_true", help="Deprecated. Enable temporal clustering of pathways post-analysis. Prefer the 'cluster' sub-command.")
    calc_parser.add_argument("--cluster_threshold", type=float, default=6.0, help="Deprecated. Frechet threshold for the inline clustering. Same default as 'gephyra cluster --threshold'.")
    calc_parser.add_argument("--cluster_output", default="clustered_pathways.json", help="Deprecated. Output file for the inline clustering.")
    
    # cluster sub-command  (NEW – decoupled from 'calculate')
    cluster_parser = subparsers.add_parser("cluster", help="Cluster pathways from a finished calculation without re-running the MD analysis.",)
    cluster_parser.add_argument("--data", required=True, help="Input JSONL file generated by the 'calculate' sub-command.")
    cluster_parser.add_argument("--threshold", type=float, default=6.0,
        help="9D feature-vector distance threshold (Å) for average-link clustering. "
         "Lower values produce finer clusters. "
         "This metric computes the Fréchet distance between 3D path coordinates. "
         "Recommended range: 3.0–8.0 Å depending on system flexibility.")
    cluster_parser.add_argument("--coarse_trigger", type=int, default=1000,
        help="Number of paths below which the 9D coarse screening pass is bypassed "
             "and Fréchet distance is computed directly on all paths. "
             "Below this threshold, the Fréchet computation is fast enough that "
             "the coarse filter adds risk without benefit. "
             "Default: 1000 (≈500,000 pairs, completes in seconds on a modern CPU). "
             "Safe range: 500–2000 depending on available CPU time.")
    cluster_parser.add_argument("--coarse_threshold", type=float, default=None,
        help="9D feature-vector distance threshold (Å) for the coarse screening pass. "
         "Because it combines three 3D displacements, its numerical scale is up to "
         "sqrt(3) ≈ 1.73x larger than the Fréchet threshold. By default, it is "
         "calculated as threshold / sqrt(3).")
    cluster_parser.add_argument("--max_paths", type=int, default=60000, help="Hard cap on number of paths sent to the distance matrix. "
         "If exceeded, the top N paths by occupancy are used. "
         "Prevents out-of-memory crashes on large trajectories.")
    cluster_parser.add_argument("--output", default="clustered_pathways.json", help="Output JSON file for the cluster summary.")
    
    # --- Visualize Subcommand ---
    vis_parser = subparsers.add_parser("visualize", help="Generate visualization scripts from calculation results.")
    vis_parser.add_argument("--data", required=True, help="Input JSONL file generated by the 'calculate' command.")
    vis_parser.add_argument("--format", choices=["vmd", "pymol", "chimera"], default="vmd", help="Target visualization software.")
    vis_parser.add_argument("--mode", choices=["density", "frame", "cluster"], default="density", help="Visualization mode: 'density' (all frames), 'frame' (single frame), or 'cluster' (clustered medoids).")
    vis_parser.add_argument("--frame", type=int, default=None, help="Frame index to visualize (only used if mode='frame').")
    vis_parser.add_argument("--cluster_id", type=int, default=None, help="Specific cluster ID to visualize (only used if mode='cluster'). If None, visualizes all clusters.")
    vis_parser.add_argument("--output", default="pathways_viz", help="Output script file name or prefix.")
    vis_parser.add_argument("--max_bond_draw_dist", type=float, default=6.0,
        help="Maximum Euclidean distance (Å) between two connected path atoms "
             "before the cylinder is treated as a PBC artifact and skipped. "
             "Should be slightly larger than your --coarse_cutoff value. "
             "Default: 6.0 Å (safe for the default coarse_cutoff of 4.5 Å).")

    args = parser.parse_args()

    if args.command == "calculate":
        run_analysis(
            topo_file=args.topo,
            traj_file=args.traj,
            root_sel=args.root,
            water_sel=args.water,
            stride=args.stride,
            max_depth=args.max_depth,
            min_depth=args.min_depth,
            cooperativity=args.cooperativity,
            coarse_cutoff=args.coarse_cutoff,
            output_file=args.output,
            csv_file=args.csv,
            cluster=args.cluster,
            cluster_threshold=args.cluster_threshold,
            cluster_output=args.cluster_output
        )

    elif args.command == "cluster":
        cluster_pathways(
            data_file=args.data,
            threshold=args.threshold,
            coarse_threshold=args.coarse_threshold,
            coarse_trigger=args.coarse_trigger,
            max_paths=args.max_paths,
            output_file=args.output,
        )
        
    elif args.command == "visualize":
        run_visualization(
            data_file=args.data,
            format=args.format,
            mode=args.mode,
            frame_idx=args.frame,
            cluster_id=args.cluster_id,
            output_file=args.output,
            max_bond_draw_dist=args.max_bond_draw_dist,
        )

if __name__ == "__main__":
    main()
